language: go
go:
- 1.13
addons:
  sonarcloud:
    organization: "jaedle-github"
    token:
      secure: "Ay12EFIPVwGjrRh7Ycydx3j346rpzSGVqMD0U5fcbRTLgnPRcf1/U+jWLunS1UdeCSFOQR34Rx6gdRfEgv77+vVhge9aZHdcQvgcazWY7vs+C5ECE5eoATvBO7AMu0hI6m0VNb9wFT6mMkXclzHRklWofzWqw1vLdPGKGr4lpjMRk3kj+apaVxhuj1BBKoOw0w2ar9qgLlflA7MCAxRx/VTsdOfAalJZ8f8xn+SbkfvfLS/PASqiyglit0Gr7Wy7kc9PVeXsSf8actQj+NRb9pqNQ5/BRkX0QynnkoUNXUu6upnm0MwFaUpoMvGLRpAnALSaQSj5Knl1g/EP7OLU2/6O/E7vwU/IEGjxz9lumf1S++5nCeD2KTgkIgbrJPYbaB4I+KXkVqdpEeolsKwBgEqNOUlybvex4FTdM8XubkKUxiyCrxvA8q6CtV3S/z0klsM2kC5CIExZUB+YHejFEZAANu/oXIW+zW1zb15vw53WTv71TAHRxjzxcZh553Z5qdKQYhzboSXt5D6Aqw8y6Ckm9MMsBaHb6nhioMVQVOCoImgmqAL0MW5W76HI776PwuAOYXT0bXeIEYoYRiyW7BZdZMGIjIweeKF/bCUqOZVf/FTBMrEfXwrESLGE/asBO3fnf9kVSrL0rxegTjqcXPmW5ByzaJJgz5LDLdUOulQ="
env:
  matrix:
  - GO111MODULE=on
  global:
    secure: W2uqJnQ/uS3d0wOjV72u6uAkj6degXr+dNpsjBMp2EV40u9/3DQWxq+mODRUS/PGsXUY1hOIAR1K+zNoFA0ermN0oooDmBlGO50OabAi4GiGWvHNlXLDm219fduKhzMYyO5Ta5+cJi1vWaZ6A/XDFUBDRs9dduBmqnfavg9yLauvHI8yIGph2n++pbQy9ZYuiLGAAlp65wLwMn8Ck5h0YVV63J0q981pegOuRLvxUx2rCSS6QKpIQz08fjxbuaPeK7C5WocXAU8BMsAa0dHK4x56hCb3lsUByc90+xVDBOZvVsN2bT8VSJLCAOi1Gs962HgVBVcg0/mLIsxwWep74F/g/VRmrEbdrm0zQRaVcFdX1HcyjylZdOC3WP7jz6m+Ojp3+fYunun/b9hgpBl7Y37whTt0Ojl7kTH2tFVmG2aEZsPJbNapcYDOmeF/Yw31XtUQ+jnLfU9ZjQehCDJnYaZf/Pvt4lYTO5VqWkiPdqAfUq0QW8aRJ2V/fjIjkao7DsTax4W5i/1VZ33/25GG3LFAhfeQZjO1ZGgWyhb7epLN4Hn/upk/zd0N3IHx9HLGGjWQ4CABwXuxLcyrLtQX68nhE7pZiRbbpnxJe2cUMg8Oi7XT2O38tOQdHAmIP0RGmfqyxnDABW8TY7hm5SODWKpTKss5mZrMn9s3M7FAXzU=
before_install:
- "$(cd $HOME && curl -s https://raw.githubusercontent.com/go-task/task/master/install-task.sh
  | sh)"
- export PATH="$PATH:$HOME/bin:$HOME/gopath/bin"
- task install-tools
install:
- task install
- task verify
script:
- task test
- task integration-test
- task lint
- task coveralls-analysis
- task sonar-analysis
