name: test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install task
        run: brew install go-task/tap/go-task
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - uses: actions/checkout@v2
