name: test
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$HOME/bin" >> "$GITHUB_PATH"
          echo "$HOME/gopath/bin" >> "$GITHUB_PATH"
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - name: install
        run: |
          task install-tools && \
          task install
      - name: verify preconditions
        run: task verify
      - run: task test integration-test
      - run: task lint
      - run: task coveralls-analysis
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
