name: test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - uses: actions/checkout@v2
