name: test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - name: install
        run: |
          task install-tools && \
          task install
      - run: export PATH="$PATH:$HOME/bin:$HOME/gopath/bin"
      - name: verify preconditions
        run: PATH="$PATH:$HOME/bin:$HOME/gopath/bin" task verify
      - run: PATH="$PATH:$HOME/bin:$HOME/gopath/bin" task test integration-test
      - run: PATH="$PATH:$HOME/bin:$HOME/gopath/bin" task lint
